import { DM_sans } from "next/font/google";
import "./globals.css";

const DM_sans = DM_sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${DM_sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
